export const CATEGORIES = [
  'Food',
  'Transport',
  'Shopping',
  'Bills',
  'Entertainment',
  'Health',
  'Education',
  'Other',
];

export const CATEGORY_CONFIG = {
  Food: {
    name: 'Food',
    icon: 'Utensils',
    bg: 'bg-orange-50 text-orange-600 border-orange-200',
    badge: 'bg-orange-100 text-orange-700',
    barColor: 'from-amber-500 to-orange-500',
    accent: '#f97316',
    emoji: '🍔',
  },
  Transport: {
    name: 'Transport',
    icon: 'Car',
    bg: 'bg-blue-50 text-blue-600 border-blue-200',
    badge: 'bg-blue-100 text-blue-700',
    barColor: 'from-blue-500 to-cyan-500',
    accent: '#3b82f6',
    emoji: '🚗',
  },
  Shopping: {
    name: 'Shopping',
    icon: 'ShoppingBag',
    bg: 'bg-pink-50 text-pink-600 border-pink-200',
    badge: 'bg-pink-100 text-pink-700',
    barColor: 'from-pink-500 to-rose-500',
    accent: '#ec4899',
    emoji: '🛍️',
  },
  Bills: {
    name: 'Bills',
    icon: 'Receipt',
    bg: 'bg-amber-50 text-amber-600 border-amber-200',
    badge: 'bg-amber-100 text-amber-700',
    barColor: 'from-amber-500 to-yellow-500',
    accent: '#eab308',
    emoji: '⚡',
  },
  Entertainment: {
    name: 'Entertainment',
    icon: 'Film',
    bg: 'bg-purple-50 text-purple-600 border-purple-200',
    badge: 'bg-purple-100 text-purple-700',
    barColor: 'from-purple-500 to-indigo-500',
    accent: '#a855f7',
    emoji: '🎬',
  },
  Health: {
    name: 'Health',
    icon: 'HeartPulse',
    bg: 'bg-emerald-50 text-emerald-600 border-emerald-200',
    badge: 'bg-emerald-100 text-emerald-700',
    barColor: 'from-emerald-500 to-teal-500',
    accent: '#10b981',
    emoji: '💊',
  },
  Education: {
    name: 'Education',
    icon: 'GraduationCap',
    bg: 'bg-indigo-50 text-indigo-600 border-indigo-200',
    badge: 'bg-indigo-100 text-indigo-700',
    barColor: 'from-indigo-500 to-blue-600',
    accent: '#6366f1',
    emoji: '📚',
  },
  Other: {
    name: 'Other',
    icon: 'Package',
    bg: 'bg-slate-50 text-slate-600 border-slate-200',
    badge: 'bg-slate-100 text-slate-700',
    barColor: 'from-slate-500 to-zinc-500',
    accent: '#64748b',
    emoji: '📦',
  },
};
